---
all:
  children:
    firewalls:
      hosts:
        firewall:
          ansible_host: 192.168.10.254

    vlan10_services:
      hosts:
        dhcp:
          ansible_host: 192.168.10.1
        dns:
          ansible_host: 192.168.10.2
        rsyslog:
          ansible_host: 192.168.10.3

    dhcp_servers:
      hosts:
        dhcp:

    dns_servers:
      hosts:
        dns:

    vlan20_web:
      hosts:
        web:
          ansible_host: 192.168.20.1

    vlan30_clients:
      hosts:
        m1:
          ansible_host: 192.168.30.1
        m2:
          ansible_host: 192.168.30.2
        m3:
          ansible_host: 192.168.30.3
        nfs:
          ansible_host: 192.168.30.4

    dhcp_clients:
      hosts:
        dns:
        rsyslog:
        web:
      children:
        vlan30_clients:

  vars:
    ansible_user: ansadmin
    ansible_become: true
