---
- name: Installer l'outil client NFS sur le serveur Web
  ansible.builtin.apt:
    name: nfs-common
    state: present
    update_cache: true

- name: S'assurer que le point de montage local du backup existe
  ansible.builtin.file:
    path: /mnt/nfs_backup
    state: directory
    owner: root
    group: root
    mode: '0700'

- name: Monter le partage NFS dédié aux sauvegardes
  ansible.posix.mount:
    path: /mnt/nfs_backup
    src: 192.168.30.4:/home/backup_db
    fstype: nfs
    opts: rw,sync,hard,intr,nfsvers=4,proto=tcp
    state: mounted
  register: mount_result
  until: mount_result is succeeded


- name: Installer le paquet cron
  ansible.builtin.apt:
    name: cron
    state: present
    update_cache: true

- name: S'assurer que le service cron est démarré
  ansible.builtin.systemd:
    name: cron
    state: started
    enabled: true

- name: Créer la tâche Cron pour la sauvegarde toutes les 10 minutes
  ansible.builtin.cron:
    name: "Sauvegarde base de donnees Intranet"
    minute: "*/10"
    user: root
    job: "/usr/bin/mysqldump -u root -proot intranet_db > /mnt/nfs_backup/intranet_backup_$(date +\\%Y\\%m\\%d_\\%H\\%M).sql"
    state: present
...