---
- name: Install MariaDB and Python dependency
  ansible.builtin.apt:
    name:
      - mariadb-server
      - python3-pymysql
    state: present
    update_cache: true

- name: Enable and start MariaDB
  ansible.builtin.service:
    name: mariadb
    state: started
    enabled: true
