---
- name: Install DHCP client package
  ansible.builtin.apt:
    name: isc-dhcp-client
    state: present
    update_cache: true

- name: Configure network interface to use DHCP
  ansible.builtin.template:
    src: interfaces.j2
    dest: /etc/network/interfaces
    owner: root
    group: root
    mode: '0644'
    backup: true
  notify: Restart networking
